"""build123d-drafting — drawing annotation helpers for build123d.

Every annotation builder is a native build123d ``BaseSketchObject`` subclass —
the returned object *is* a ``Sketch`` (composable in ``BuildSketch``,
``.moved()``-able, exportable directly). Import directly in your drawing
scripts — no MCP server required::

    from build123d_drafting import (
        Dimension, SafeDimension, Leader, Centerline,
        view_axes, lint_drawing, find_interferences, find_overlaps, LintIssue,
    )

For automated drawing generation from a solid, see the ``draftwright`` package.
"""

from build123d_drafting.features import (
    BoltCircle,
    BossFeature,
    CounterBore,
    HoleFeature,
    LinearArray,
    RectGrid,
    analyse_cylinders,
    feature_diameters,
    find_bosses,
    find_hole_patterns,
    find_holes,
)
from build123d_drafting.helpers import (
    Centerline,
    CenterlineCircle,
    CenterMark,
    CompositeFeatureControlFrame,
    DatumFeature,
    DatumTarget,
    Dimension,
    FeatureControlFrame,
    HoleCallout,
    Leader,
    LintIssue,
    Note,
    SafeDimension,
    SurfaceFinish,
    TextBlock,
    TitleBlock,
    ViewCoordinates,
    annotate,
    clear_page,
    draft_preset,
    find_interferences,
    find_overlaps,
    format_drawing_scale,
    leader_offset,
    lint_drawing,
    place_dims,
    place_labels,
    set_page,
    view_axes,
)

__all__ = [
    "BoltCircle",
    "BossFeature",
    "CenterMark",
    "CenterlineCircle",
    "Centerline",
    "CompositeFeatureControlFrame",
    "CounterBore",
    "DatumFeature",
    "DatumTarget",
    "Dimension",
    "FeatureControlFrame",
    "HoleCallout",
    "HoleFeature",
    "Leader",
    "LinearArray",
    "LintIssue",
    "Note",
    "RectGrid",
    "SafeDimension",
    "SurfaceFinish",
    "TextBlock",
    "TitleBlock",
    "ViewCoordinates",
    "analyse_cylinders",
    "annotate",
    "clear_page",
    "draft_preset",
    "feature_diameters",
    "find_bosses",
    "find_hole_patterns",
    "find_holes",
    "find_interferences",
    "find_overlaps",
    "format_drawing_scale",
    "leader_offset",
    "lint_drawing",
    "place_dims",
    "place_labels",
    "set_page",
    "view_axes",
]
